export const ADD_TO_CHECKOUT = 'ADD_TO_CHECKOUT'
export const GET_CHECKOUT = 'GET_CHECKOUT'
export const ACCEPT_ORDER = 'ACCEPT_ORDER' 
// export const EDIT_CART_DEC = 'EDIT_CART_DEC' 
// export const DELETE_CART = 'DELETE_CART'
// export const DELETE_ALL_CART = 'DELETE_ALL_CART'
