
export const CREATE_PRODUCTS = 'CREATE_PRODUCTS'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const EDIT_PRODUCT = 'EDIT_PRODUCT' 
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS'
export const GET_LENGTH = 'GET_LENGTH'

